### ISSUE TITLE
Several compilers are not listed here

### ISSUE THREAD

**Issue by jarble** [dbohdan/compilers-targeting-c#46]
There are several compilers targeting C that are not yet included in this list:

* [ts2c](https://github.com/andrei-markeev/ts2c) compiles a subset of JavaScript and TypeScript into C.
* [CLiCC](https://www.informatik.uni-kiel.de/~wg/clicc.html) is a Common Lisp to C compiler.
* [NectarJS](https://github.com/NectarJS/nectarjs/issues/46#issuecomment-480959913) compiles JavaScript to C.

**Comment by dbohdan** [comment]
Added all three in 605bcbabb24f051b219f0973817436cdc4049e1a, 44e307500e635bb8df15103bbdf55694a295a4b9, fe999386c376513e615341df44b5e818763c297e.  Thank you for contributing!
