### ISSUE TITLE
Wasmdec

### ISSUE THREAD

**Issue by jarble** [dbohdan/compilers-targeting-c#60]
There's a compiler called [wasmdec](https://github.com/wwwg/wasmdec) that converts WebAssembly modules to C source code. Should it be included in this list?

**Comment by dbohdan** [comment]
>Should it be included in this list?

I think it should.  Thanks for suggesting it.

**Comment by jarble** [comment]
@dbohdan An alternative to wasmdec is [wasm2c](https://github.com/WebAssembly/wabt/tree/master/wasm2c). It should probably be listed here too.

**Comment by dbohdan** [comment]
That's a good suggestion.  Added in 783cfb2.
